version: 0.2

phases:
  build:
    commands:
      - echo "Preparando paquete para Lambda…"
      - rm -rf dist
      - mkdir -p dist
      - cp src/index.js dist/index.js

artifacts:
  base-directory: dist
  files:
    - '**/*'
